### ISSUE TITLE
Suggestion for the icon of "Overview of DCs"

### ISSUE THREAD

**Issue by ocean0609** [Hong-Kong-Districts-Info/dashboard-hkdistrictcouncillors#40]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I suggest using 👤 as the icon of "Overview of a DC"  would be better than using 🔍
cause i kind of mix up the 🔍 with "search" 
maybe it is better to move the search bar can put there above "Overview of a DC"

**Describe alternatives you've considered**
Might follow their layout of this app
![IMG_6532](https://user-images.githubusercontent.com/67370580/89024373-92661300-d357-11ea-83c8-9e0cc0de9e9c.jpg)

**Comment by avisionh** [comment]
Good spot and suggestion! 

For the search box being moved to the left, I don't think it would be suitable for the way our current website is designed since the existing search functionality affects the "Overview of a DC" tab only. If we moved it to the sidebar, it would indicate that the search there affects the website as a whole, so it would affect the "List of DCs" and "Construction" tabs.
